[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]

bank-rewards = "CtNhstCC9DPUMYZKvaM7uMFGxJeHQLxBwLSY3qHarTf5"
# rewards-bank = "7p4EhrzHyxyMuDStn4rPn5x8MMtwSrrNfzjbJChtaA3Y"

sol_trust = "BBoAqxz7AfBvtkDgj2XtjG9kMmUEciSg6xmyLCJmzNGY"

[idl]
out = "target/idl"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
